### ISSUE TITLE
[epic] analytics

### ISSUE THREAD

**Issue by catdad** [catdad/raw-viewer#208]
- [x] reserve block of IDs for internal use
- [x] track versions
- [x] track main screen
- [x] track about screen
- [x] track updater screen
- [x] track keyboard shortcuts screen
- [x] track file types being opened - #223 
- [x] track file conversion times - #224 & #226
- [x] track platform metadata (OS, CPU, etc.) - #231 
- [x] track number of screens and screen size - #233
- [x] track raw conversion times
- [x] track when users have exited the overlay (count as main view?)
- [x] explain what analytics are used for - #235 
- [x] opt out option - #237

**Comment by catdad** [comment]
It looks like the app view in analytics does not allow events (or at least not anymore). However, the website view does not allow app data like versions. I guess I am forced to use the app view, and so I'll have to track versions separately.
